version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - productdata:/data/db

  shoppingcartdb:
    container_name: shoppingcartdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=DiscountDb
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    volumes:
      - discountdata:/var/lib/mysql
  
  paymentdb:
    container_name: paymentdb
    restart: always
    volumes:
      - paymentdata:/data/db

  identitydb:
    container_name: identitydb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MsSQL123456
    ports:
      - "1433:1433"
    volumes:
      - identitydata:/var/opt/mssql

  rabbitmqserver:
    container_name: rabbitmqserver
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  product.api:
    container_name: product.api
    restart: always
    depends_on:
      - productdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CourseDbSettings:ConnectionString=mongodb://productdb:27017"
      - "CourseDbSettings:DatabaseName=CourseDb"
      - "CourseDbSettings:CollectionName=Courses"
    ports:
      - "9000:80"

  shoppingcart.api:
    container_name: shoppingcart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=shoppingcartdb:6379"
      - "DiscountUrl:GrpcServer=http://grpcserver"
      - "RabbitmqUrl:HostAddress=amqp://guest:guest@rabbitmqserver:5672"
    depends_on:
      - shoppingcartdb
      - grpcserver
    ports:
      - "9001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MySqlConnection=server=discountdb;port=3307;database=DiscountDb;user=root;password=mysql"
    depends_on:
      - discountdb
    ports:
      - "9002:80"

  grpcserver:
    container_name: grpcserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MySqlConnection=server=discountdb;port=3307;database=DiscountDb;user=root;password=mysql"
    depends_on:
      - discountdb
    ports:
      - "9003:80"
 
  payment.api:
    container_name: payment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "BillDbSettings:ConnectionString=mongodb://paymentdb:27017"
      - "BillDbSettings:DatabaseName=BillDb"
      - "BillDbSettings:CollectionName=Bills"
      - "RabbitmqUrl:HostAddress=amqp://guest:guest@rabbitmqserver:5672"
    ports:
      - "9004:80"
    depends_on:
      - paymentdb
      - rabbitmqserver

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "JwtKeyOptions:PrivateKeyFilePath=/shared/keys/private.xml"
      - "JwtKeyOptions:PublicKeyFilePath=/shared/keys/public.xml"
      - "ConnectionStrings:DbConnection=Server=identitydb;Database=Identity;User ID=sa;Password=MsSQL123456;Integrated security=False;TrustServerCertificate=true;"
    ports:
      - "9005:80"
    depends_on:
      - identitydb

  ocelotgateway:
    container_name: ocelotgateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "JwtKeyOptions:PrivateKeyFilePath=/shared/keys/private.xml"
      - "JwtKeyOptions:PublicKeyFilePath=/shared/keys/public.xml"
    ports:
      - "9006:80"